language: generic
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    language: cpp
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
          - libatlas-base-dev
          - libblas-dev
  - os: osx
    sudo: required
    osx_image: xcode11
    language: c++
    compiler: clang

before_install:
  - |
    python3 -V
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py --user
    python3 -m pip install pip --upgrade
    git clone https://github.com/Dekken/maiken --depth 10 -b master maiken
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      make bsd -C maiken CXX="clang++" & MKN=$!
      find /usr/local/lib -name "libmkl*"
      wait $MKN
    elif [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo ln -fs /usr/bin/gcc-8 /usr/local/bin/gcc; sudo ln -fs /usr/bin/g++-8 /usr/local/bin/g++;
      make nix -C maiken & MKN=$!
      export PATH="$PWD:/opt/python/3.7.3/bin:$PATH"
      wait $MKN
    fi
  - mv maiken/mkn .

script:
  - |
    export KUL_GIT_CO="--depth 3"
    export MKN_LIB_LINK_LIB=1
    export PYTHON=python3
    export XTRA="-x $PWD/res/ci/travis-${TRAVIS_OS_NAME}.yaml"
    source $PWD/res/ci/travis-${TRAVIS_OS_NAME}.sh
    exit 0
