version: 0.1.{build}

branches:
  only:
    - master

max_jobs: 1

image:
- Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64
configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir -p "C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt"
  - bash -c "PATH=\"$PWD:/c/Python36-x64/:/c/Program Files/Git/usr/bin:$PATH\"; ./res/ci/appvey.sh"

# artifacts:
#   - path: '*.tar'

# deploy:
# - provider: BinTray
#   username: dekken
#   api_key:
#     secure: FGDIE5oZsFn49kRhIK98X2JAqXwvReVl1nSlKNlo3pYCtosD2r9YfkHHhAJcjcyE
#   subject: dekken
#   repo: maiken
#   package: mkn
#   publish: true
#   override: true
#   explode: true
#   artifact: /.*\.tar/
#   version: master
