version: 0.1.{build}

max_jobs: 1

image:
- Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64
configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - IF NOT EXIST C:\ProgramData\chocolatey\bin\swig.exe choco install res\ci\swig.4.0.0.nupkg --yes --limit-output #> $null
  - cat C:\ProgramData\chocolatey\logs\chocolatey.log

build_script:
  - cp "C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe" %CD%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - mkdir -p "C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt"
  - bash -c "PATH=\"$PWD:/c/Python37-x64/:/c/Program Files/Git/usr/bin:$PATH\"; ./res/ci/appvey.sh"
